import { Link, useNavigate } from '@tanstack/react-router';
import { Heart, ShoppingBag, Search, UserRound, Menu, Sun, Moon, ArrowRight, Instagram, Facebook, Twitter, X } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { products, categories, money, discount, type Product } from '@/data/products';
import { useShop } from '@/context/ShopContext';

export function Navbar() {
  const { count, wishlist, theme, toggleTheme, user } = useShop();
  const [menu, setMenu] = useState(false); const [search, setSearch] = useState('');
  const navigate = useNavigate();
  const submit = (e: FormEvent) => { e.preventDefault(); navigate({ to: '/products', search: { q: search.trim() } }); setMenu(false); };
  return <><div className="announcement">Complimentary shipping on orders over ₹4,999 <span>•</span> Curated for the way you live</div><header className="site-header"><div className="container topnav"><Button variant="ghost" size="icon" className="mobile-menu" aria-label="Open menu" onClick={() => setMenu(!menu)}><Menu /></Button><Link to="/" className="brand">LUXE<span>MART</span><i>.</i></Link><nav aria-label="Main navigation" className={menu ? 'nav-links open' : 'nav-links'}><Link to="/" onClick={() => setMenu(false)}>Home</Link><Link to="/products" search={{ q: '' }} onClick={() => setMenu(false)}>Shop all</Link><Link to="/categories" onClick={() => setMenu(false)}>Categories</Link><Link to="/about" onClick={() => setMenu(false)}>Our story</Link><Link to="/contact" onClick={() => setMenu(false)}>Contact</Link></nav><form className="header-search" onSubmit={submit} role="search"><Search size={18}/><input aria-label="Search products" placeholder="Search for something special..." value={search} onChange={e => setSearch(e.target.value)} /><Button variant="ghost" size="icon" aria-label="Submit search" type="submit"><ArrowRight size={17}/></Button></form><div className="nav-actions"><Button variant="ghost" size="icon" onClick={toggleTheme} aria-label={theme === 'light' ? 'Switch to dark mode' : 'Switch to light mode'} title="Change theme">{theme === 'light' ? <Moon/> : <Sun/>}</Button><Link aria-label="Account" title="Account" to={user ? '/profile' : '/login'}><UserRound size={21}/></Link><Link aria-label={`Wishlist, ${wishlist.length} items`} title="Wishlist" to="/wishlist" className="nav-icon"><Heart size={21}/>{wishlist.length > 0 && <span className="count-badge">{wishlist.length}</span>}</Link><Link aria-label={`Cart, ${count} items`} title="Cart" to="/cart" className="nav-icon"><ShoppingBag size={21}/>{count > 0 && <span className="count-badge">{count}</span>}</Link></div></div></header></>;
}
export function Footer() { return <footer className="site-footer"><div className="container footer-grid"><div><Link to="/" className="brand">LUXE<span>MART</span><i>.</i></Link><p>Thoughtfully chosen, beautifully lived. Everyday essentials with an extraordinary point of view.</p><div className="socials"><Instagram size={18}/><Facebook size={18}/><Twitter size={18}/></div></div><div><h3>Explore</h3><Link to="/products" search={{ q: '' }}>Shop all</Link><Link to="/categories">Categories</Link><Link to="/wishlist">Wishlist</Link><Link to="/cart">Your bag</Link></div><div><h3>Information</h3><Link to="/about">Our story</Link><Link to="/contact">Contact us</Link><Link to="/profile">Your account</Link></div><div><h3>Stay in the know</h3><p>A little inspiration, delivered occasionally.</p><form onSubmit={e => { e.preventDefault(); import('sonner').then(({toast}) => toast.info('Demo only — no email was subscribed.')); }} className="subscribe"><input type="email" aria-label="Email for updates" placeholder="Your email address" required/><Button size="icon" aria-label="Subscribe"><ArrowRight/></Button></form></div></div><div className="container footer-bottom"><span>© 2026 LuxeMart. All rights reserved.</span><span>Made for the moments that matter.</span></div></footer>; }
export function ProductCard({ product: p }: { product: Product }) { const { addToCart, toggleWishlist, wishlist } = useShop(); return <article className="product-card"><div className="product-image"><Link to="/products/$id" params={{ id: p.id }} search={{q:""}}><img src={p.image} loading="lazy" width="512" height="512" alt={p.name}/></Link>{p.new && <span className="product-tag">NEW</span>}<Button variant="ghost" size="icon" aria-label={wishlist.includes(p.id) ? `Remove ${p.name} from wishlist` : `Add ${p.name} to wishlist`} className={`heart-btn ${wishlist.includes(p.id) ? 'is-active' : ''}`} onClick={() => toggleWishlist(p.id)}><Heart size={18} fill={wishlist.includes(p.id) ? 'currentColor' : 'none'}/></Button>{p.available && <Button className="quick-add" onClick={() => addToCart(p.id)}><ShoppingBag size={16}/> Add to bag</Button>}</div><div className="product-meta"><span>{p.category}</span><span className="stars">★ <b>{p.rating}</b></span></div><Link to="/products/$id" params={{ id: p.id }} search={{q:""}} className="product-name">{p.name}</Link><div className="price-line"><strong>{money(p.price)}</strong><del>{money(p.originalPrice)}</del><span>{discount(p)}% off</span></div></article>; }
export function ProductGrid({ items }: { items: Product[] }) { return <div className="product-grid">{items.map(p => <ProductCard key={p.id} product={p}/>)}</div>; }
export function CategoryCard({ category, index }: { category: string; index: number }) { const images = [products[4], products[0], products[1], products[2], products[3]]; return <Link to="/products" search={{ q: category }} className="category-card"><img src={(images[index] || products[0])?.image || ''} alt={category} loading="lazy"/><span>{category} <ArrowRight size={17}/></span></Link>; }
export function PageIntro({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) { return <div className="page-intro"><div className="container"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{children && <p>{children}</p>}</div></div>; }
export function EmptyState({ title, detail, action = 'Explore the collection' }: { title: string; detail: string; action?: string }) { return <div className="empty-state"><ShoppingBag size={42} strokeWidth={1.3}/><h2>{title}</h2><p>{detail}</p><Button asChild><Link to="/products" search={{ q: '' }}>{action} <ArrowRight size={16}/></Link></Button></div>; }
export function RemoveIcon({ onClick, label }: { onClick: () => void; label: string }) { return <Button variant="ghost" size="icon" onClick={onClick} aria-label={label}><X size={18}/></Button>; }
export { categories, products, money, discount };
